version: '3'

services:

  bot:
    build: .
    command: python -u main.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: unless-stopped
    links:
      - pymongo

  pymongo:
    image: mongo:latest
    ports:
      - "27017:27017"